version: '3'
services:
  app:
    build: 
      context: ./images/app
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
    networks:
      - default
    tty: true

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dump/:/dump
    ports:
    - 3306:3306

volumes:
  mysql-data:

networks:
  default:
    driver: bridge
