version: '3'
services:
  app:
    build:
      context: ./images/app
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
    networks:
      - default
    tty: true

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dump/:/dump
    ports:
    - 3306:3306

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=docker-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - network.bind_host=0.0.0.0
      - network.host=0.0.0.0

volumes:
  mysql-data:

networks:
  default:
    driver: bridge
